# Apache Spark installation tasks

- name: Download and extract archive
  unarchive: src={{mirrors | random}}/spark/spark-{{apache_spark_version}}/spark-{{apache_spark_version}}-bin-without-hadoop.tgz dest=/opt creates=/opt/spark-{{apache_spark_version}}-bin-without-hadoop copy=no owner=root group=root

- name: Rename extracted directory
  command: mv /opt/spark-{{apache_spark_version}}-bin-without-hadoop /opt/apache-spark-{{apache_spark_version}}-without-hadoop creates=/opt/apache-spark-{{apache_spark_version}}-without-hadoop

- name: Create home directory
  file: src=/opt/apache-spark-{{apache_spark_version}}-without-hadoop dest={{apache_spark_home}} state=link
