# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"

  # Network settings
  config.vm.hostname = "ons-business-dev"
  config.vm.network "private_network", ip: "192.168.33.100"

  # VirtualBox settings
  config.vm.provider "virtualbox" do |vm|
    vm.name = "ons-bussiness-dev"
    vm.cpus = 2
    vm.memory = 4096
  end

  config.vm.provision "ansible_local" do |ansible|
    # ansible.verbose = "vv"
    ansible.provisioning_path = "/home/vagrant/sync/provisioning"
    ansible.playbook = "playbook.yaml"
    ansible.sudo = true
  end
end
