---
- name: Install network tools
  yum: name=net-tools state=latest

- name: Configure Elasticsearch system configuration.
  template: src=elasticsearch.j2 dest=/etc/sysconfig/elasticsearch owner=root group=root mode=0644
  notify: restart elasticsearch

- name: Configure Elasticsearch.
  template: src=elasticsearch.yml.j2 dest=/etc/elasticsearch/elasticsearch.yml owner=root group=root mode=0644
  notify: restart elasticsearch

- name: Configure systemd service for Elasticsearch
  template: src=elasticsearch.service.j2 dest=/usr/lib/systemd/system/elasticsearch.service
  notify: 
  - reload daemon
  - restart elasticsearch

- name: Check if path exist.
  stat: path=/usr/share/elasticsearch/plugins/head
  register: check_path

- name: Include elasticsearch head install
  command: /usr/share/elasticsearch/bin/plugin install mobz/elasticsearch-head
  when: (ansible_virtualization_type == "virtualbox" and "client" in ansible_hostname and check_path.stat.exists == false)
